### ISSUE TITLE
Request for Centroid (Pick-and-Place) File

### ISSUE THREAD

**Issue by Dennisjoch** [ShikyC/Sanro-Arduino#19]
Hello,

I am currently using the PCB design files from this project, but I need a Centroid (Pick-and-Place) file for assembly purposes. Unfortunately, I only have the Gerber files and do not have the original PCB design files to generate the Centroid file myself.

Would it be possible for you to provide a Centroid file for this project?

Thank you very much for your assistance!

Best regards, Dennis Joch

**Comment by ShikyC** [comment]
Unfortunately I have been modifying the origianl PCB project recently for a new release so I can't generate the Centroid file for it. Sorry for my poor version control but I did lose this version of the PCB design file. I'll release a new version with an intergrated ESP32 chip so the users don't need to buy the DevKit board separately.

My suggestion is, because the PCB is so simple that you can buy the components listed in the BOM file and hand-solder it. Or if you need it urgently and live in the U.S., I can ship one to you for free (excluding the shipping fee).

**Comment by Dennisjoch** [comment]
Hey, it's all good. After some head-scratching and overpriced offers on Fiverr, the customer support from PCBWay got in touch and was able to help me based on your project preview image and my labeling. Just as I was about to cancel the assembly because I thought I'd have to solder it myself. Thank you for your willingness to help, and great project! Thanks.
